In [1]:
import numpy as np

In [5]:
Day=np.arange(1,11)
steps=[4335,9552,7332,4504,5335,7552,8332,6504,8965,7689]
arr=np.array([Day,steps])
arr=arr.T
arr

array([[   1, 4335],
       [   2, 9552],
       [   3, 7332],
       [   4, 4504],
       [   5, 5335],
       [   6, 7552],
       [   7, 8332],
       [   8, 6504],
       [   9, 8965],
       [  10, 7689]])

In [6]:
new_arr=arr[:,1]+1000
arr[:,1]=new_arr
arr

array([[    1,  5335],
       [    2, 10552],
       [    3,  8332],
       [    4,  5504],
       [    5,  6335],
       [    6,  8552],
       [    7,  9332],
       [    8,  7504],
       [    9,  9965],
       [   10,  8689]])

In [7]:
matched=arr[:,1]>7000
matched
new_arr=arr[matched]
new_arr

array([[    2, 10552],
       [    3,  8332],
       [    6,  8552],
       [    7,  9332],
       [    8,  7504],
       [    9,  9965],
       [   10,  8689]])